# Generated by Django 4.2.6 on 2023-10-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_product", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("count_product", models.IntegerField()),
                ("date_add_product", models.DateTimeField(auto_now_add=True)),
                ("product_img", models.ImageField(upload_to="imges_product/")),
            ],
        ),
    ]
